The-Project/gym-app/the_gym/urls.py
from django.contrib import admin
from django.urls import include, path

from users.views import users, patrons, trainers

urlpatterns = [
    path('', include('users.urls')),

    # Django Admin
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', users.SignUpView.as_view(), name='signup'),
    path('accounts/signup/patrons/', patrons.PatronSignUpView.as_view(), name='patron_signup'),
    path('accounts/signup/trainers/', trainers.TrainerSignUpView.as_view(), name='trainer_signup'),
]

The-Project/gym-app/users/urls.py
from django.urls import include, path

from .views import users, patrons, trainers

urlpatterns = [
    path('', users.home, name='home'),

    path('about/', users.about, name='about'),

    path('patrons/', include(([
        path('', patrons.RoutineListView.as_view(), name='routine_list'),
        path('goals/', patrons.PatronGoalsView.as_view(), name='patron_goals'),
        path('worked/', patrons.WorkedRoutinesListView.as_view(), name='worked_routine_list'),
        path('routine/<int:pk>/', patrons.do_routine, name='do_routine'),
    ], 'users'), namespace='patrons')),

    path('trainers/', include(([
        path('', trainers.RoutineListView.as_view(), name='routine_change_list'),
        path('routine/add/', trainers.RoutineCreateView.as_view(), name='routine_add'),
        path('routine/<int:pk>/', trainers.RoutineUpdateView.as_view(), name='routine_change'),
        path('routine/<int:pk>/delete/', trainers.RoutineDeleteView.as_view(), name='routine_delete'),
        path('routine/<int:pk>/results/', trainers.RoutineResultsView.as_view(), name='routine_results'),
        path('routine/<int:pk>/task/add/', trainers.task_add, name='task_add'),
        path('routine/<int:routine_pk>/task/<int:task_pk>/', trainers.task_change, name='task_change'),
        path('routine/<int:routine_pk>/task/<int:task_pk>/delete/', trainers.TaskDeleteView.as_view(), name='task_delete'),
    ], 'users'), namespace='trainers')),
]

The-Project/gym-app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from users.models import (Response, Task, Patron, PatronResponse,
                              Goal, User)


class TrainerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_trainer = True
        if commit:
            user.save()
        return user


class PatronSignUpForm(UserCreationForm):
    goals = forms.ModelMultipleChoiceField(
        queryset=Goal.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_patron = True
        user.save()
        patron = Patron.objects.create(user=user)
        patron.goals.add(*self.cleaned_data.get('goals'))
        return user


class PatronGoalsForm(forms.ModelForm):
    class Meta:
        model = Patron
        fields = ('goals', )
        widgets = {
            'goals': forms.CheckboxSelectMultiple
        }


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('text', 'video', )


class BaseResponseInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_mandatory_response = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_complete', False):
                    has_one_mandatory_response = True
                    break
        if not has_one_mandatory_response:
            raise ValidationError('Mark at least one response as mandatory.', code='no_mandatory_response')


class DoRoutineForm(forms.ModelForm):
    response = forms.ModelChoiceField(
        queryset=Response.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = PatronResponse
        fields = ('response', )

    def __init__(self, *args, **kwargs):
        task = kwargs.pop('task')
        super().__init__(*args, **kwargs)
        self.fields['response'].queryset = task.responses.order_by('text')

The-Project/gym-app/users/views/patrons.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import patron_required
from ..forms import PatronGoalsForm, PatronSignUpForm, DoRoutineForm
from ..models import Routine, Patron, WorkedRoutine, User


class PatronSignUpView(CreateView):
    model = User
    form_class = PatronSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'patron'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('patrons:routine_list')


@method_decorator([login_required, patron_required], name='dispatch')
class PatronGoalsView(UpdateView):
    model = Patron
    form_class = PatronGoalsForm
    template_name = 'users/patrons/goals_form.html'
    success_url = reverse_lazy('patrons:routine_list')

    def get_object(self):
        return self.request.user.patron

    def form_valid(self, form):
        messages.success(self.request, 'Goals updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, patron_required], name='dispatch')
class RoutineListView(ListView):
    model = Routine
    ordering = ('name', )
    context_object_name = 'routines'
    template_name = 'users/patrons/routine_list.html'

    def get_queryset(self):
        patron = self.request.user.patron
        patron_goals = patron.goals.values_list('pk', flat=True)
        worked_routines = patron.routines.values_list('pk', flat=True)
        queryset = Routine.objects.filter(goal__in=patron_goals) \
            .exclude(pk__in=worked_routines) \
            .annotate(tasks_count=Count('tasks')) \
            .filter(tasks_count__gt=0)
        return queryset


@method_decorator([login_required, patron_required], name='dispatch')
class WorkedRoutinesListView(ListView):
    model = WorkedRoutine
    context_object_name = 'worked_routines'
    template_name = 'users/patrons/worked_routine_list.html'

    def get_queryset(self):
        queryset = self.request.user.patron.worked_routines \
            .select_related('routine', 'routine__goal') \
            .order_by('routine__name')
        return queryset


@login_required
@patron_required
def do_routine(request, pk):
    routine = get_object_or_404(Routine, pk=pk)
    patron = request.user.patron

    if patron.routines.filter(pk=pk).exists():
        return render(request, 'patrons/worked_routine.html')

    total_tasks = routine.tasks.count()
    incomplete_tasks = patron.get_uncompleted_tasks(routine)
    total_incomplete_tasks = incomplete_tasks.count()
    progress = 100 - round(((total_incomplete_tasks - 1) / total_tasks) * 100)
    task = incomplete_tasks.first()

    if request.method == 'POST':
        form = DoRoutineForm(task=task, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                patron_response = form.save(commit=False)
                patron_response.patron = patron
                patron_response.save()
                if patron.get_uncompleted_tasks(routine).exists():
                    return redirect('patrons:do_routine', pk)
                else:
                    complete_responses = patron.routine_responses.filter(response__task__routine=routine, response__is_complete=True).count()
                    score = round((complete_responses / total_tasks) * 100.0, 2)
                    WorkedRoutine.objects.create(patron=patron, routine=routine, score=score)
                    if score < 50.0:
                        messages.warning(request, 'Try wroking harder the next time! Your completion score for the routine %s was %s.' % (routine.name, score))
                    else:
                        messages.success(request, 'Awesome work! You completed the routine %s with success! You completed %s percent of the work!' % (routine.name, score))
                    return redirect('patrons:routine_list')
    else:
        form = DoRoutineForm(task=task)

    return render(request, 'users/patrons/do_routine_form.html', {
        'routine': routine,
        'task': task,
        'form': form,
        'progress': progress
    })

The-Project/gym-app/users/views/trainers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from ..decorators import trainer_required
from ..forms import BaseResponseInlineFormSet, TaskForm, TrainerSignUpForm
from ..models import Response, Task, Routine, User


class TrainerSignUpView(CreateView):
    model = User
    form_class = TrainerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'trainer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('trainers:routine_change_list')


@method_decorator([login_required, trainer_required], name='dispatch')
class RoutineListView(ListView):
    model = Routine
    ordering = ('name', )
    context_object_name = 'routines'
    template_name = 'users/trainers/routine_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.routines \
            .select_related('goal') \
            .annotate(tasks_count=Count('tasks', distinct=True)) \
            .annotate(worked_count=Count('worked_routines', distinct=True))
        return queryset


@method_decorator([login_required, trainer_required], name='dispatch')
class RoutineCreateView(CreateView):
    model = Routine
    fields = ('name', 'goal', )
    template_name = 'users/trainers/routine_add_form.html'

    def form_valid(self, form):
        routine = form.save(commit=False)
        routine.owner = self.request.user
        routine.save()
        messages.success(self.request, 'The routine was created with success! Go ahead and add some tasks now.')
        return redirect('trainers:routine_change', routine.pk)


@method_decorator([login_required, trainer_required], name='dispatch')
class RoutineUpdateView(UpdateView):
    model = Routine
    fields = ('name', 'goal', )
    context_object_name = 'routine'
    template_name = 'users/trainers/routine_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['tasks'] = self.get_object().tasks.annotate(response_count=Count('responses'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing routines that belongs
        to the logged in user.
        '''
        return self.request.user.routines.all()

    def get_success_url(self):
        return reverse('trainers:routine_change', kwargs={'pk': self.object.pk})


@method_decorator([login_required, trainer_required], name='dispatch')
class RoutineDeleteView(DeleteView):
    model = Routine
    context_object_name = 'routine'
    template_name = 'users/trainers/routine_delete_confirm.html'
    success_url = reverse_lazy('trainers:routine_change_list')

    def delete(self, request, *args, **kwargs):
        routine = self.get_object()
        messages.success(request, 'The routine %s was deleted with success!' % routine.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.routines.all()


@method_decorator([login_required, trainer_required], name='dispatch')
class RoutineResultsView(DetailView):
    model = Routine
    context_object_name = 'routine'
    template_name = 'users/trainers/routine_results.html'

    def get_context_data(self, **kwargs):
        routine = self.get_object()
        worked_routines = routine.worked_routines.select_related('patron__user').order_by('-date')
        total_worked_routines = worked_routines.count()
        routine_score = routine.worked_routines.aggregate(average_score=Avg('score'))
        extra_context = {
            'worked_routines': worked_routines,
            'total_worked_routines': total_worked_routines,
            'routine_score': routine_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.routines.all()


@login_required
@trainer_required
def task_add(request, pk):
    routine = get_object_or_404(Routine, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.routine = routine
            task.save()
            messages.success(request, 'You may now add response options to the task.')
            return redirect('trainers:task_change', routine.pk, task.pk)
    else:
        form = TaskForm()

    return render(request, 'users/trainers/task_add_form.html', {'routine': routine, 'form': form})


@login_required
@trainer_required
def task_change(request, routine_pk, task_pk):
    routine = get_object_or_404(Routine, pk=routine_pk, owner=request.user)
    task = get_object_or_404(Task, pk=task_pk, routine=routine)

    ResponseFormSet = inlineformset_factory(
        Task,  
        Response,  
        formset=BaseResponseInlineFormSet,
        fields=('text', 'is_complete'),
        min_num=2,
        validate_min=True,
        max_num=5,
        validate_max=True
    )

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        formset = ResponseFormSet(request.POST, instance=task)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Task and response options saved with success!')
            return redirect('trainers:routine_change', routine.pk)
    else:
        form = TaskForm(instance=task)
        formset = ResponseFormSet(instance=task)

    return render(request, 'users/trainers/task_change_form.html', {
        'routine': routine,
        'task': task,
        'form': form,
        'formset': formset
    })


@method_decorator([login_required, trainer_required], name='dispatch')
class TaskDeleteView(DeleteView):
    model = Task
    context_object_name = 'task'
    template_name = 'users/trainers/task_delete_confirm.html'
    pk_url_kwarg = 'task_pk'

    def get_context_data(self, **kwargs):
        task = self.get_object()
        kwargs['routine'] = task.routine
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        task = self.get_object()
        messages.success(request, 'The task %s was deleted with success!' % task.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Task.objects.filter(routine__owner=self.request.user)

    def get_success_url(self):
        task = self.get_object()
        return reverse('trainers:routine_change', kwargs={'pk': task.routine_id})

The-Project/gym-app/users/views/users.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_trainer:
            return redirect('trainers:routine_change_list')
        else:
            return redirect('patrons:routine_list')
    return render(request, 'users/home.html')

def about(request):
    return render(request, 'users/about.html')

The-Project/gym-app/users/templates/users/trainers/routine_add_form.html
{% extends 'base.html' %}

{% block title %}Add Routine{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new routine</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new routine</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'trainers:routine_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/routine_change_form.html
{% extends 'base.html' %}

{% block title %}Routine {{ routine.name }}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ routine.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ routine.name }}
    <a href="{% url 'trainers:routine_results' routine.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'trainers:routine_change_list' %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
        <a href="{% url 'trainers:routine_delete' routine.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Tasks</strong>
        </div>
        <div class="col-2">
          <strong>Responses</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for task in tasks %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'trainers:task_change' routine.pk task.pk %}">{{ task.text }}</a>
            </div>
            <div class="col-2">
              {{ task.response_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any tasks yet. Go ahead and <a href="{% url 'trainers:task_add' routine.pk %}">add the first task</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'trainers:task_add' routine.pk %}" class="btn btn-primary btn-sm">Add task</a>
    </div>
  </div>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/routine_change_list.html
{% extends 'base.html' %}

{% block title %}My Routines{% endblock %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Routines</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Routines</h2>
  <a href="{% url 'trainers:routine_add' %}" class="btn btn-primary mb-3" role="button">Add Routine</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Routine</th>
          <th>Goal</th>
          <th>Tasks</th>
          <th>Worked</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for routine in routines %}
          <tr>
            <td class="align-middle"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></td>
            <td class="align-middle">{{ routine.goal.get_html_badge }}</td>
            <td class="align-middle">{{ routine.tasks_count }}</td>
            <td class="align-middle">{{ routine.worked_count }}</td>
            <td class="text-right">
              <a href="{% url 'trainers:routine_results' routine.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any routine yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/routine_delete_confirm.html
{% extends 'base.html' %}

{% block title %}Delete Routine {{ routine.name }}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the routine <strong>"{{ routine.name }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'trainers:routine_change' routine.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/routine_results.html
{% extends 'base.html' %}

{% block title %}Routine Results{% endblock %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ routine.name }} Results</h2>

  <div class="card">
    <div class="card-header">
      <strong>Worked Routines</strong>
      <span class="badge badge-pill badge-primary float-right">Completion Pct: {{ routine_score.average_score|default_if_none:0.0 }}</span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Patron</th>
          <th>Date</th>
          <th>Completion Pct</th>
        </tr>
      </thead>
      <tbody>
        {% for worked_routine in worked_routines %}
          <tr>
            <td>{{ worked_routine.patron.user.username }}</td>
            <td>{{ worked_routine.date|naturaltime }}</td>
            <td>{{ worked_routine.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total patrons: <strong>{{ total_worked_routines }}</strong>
    </div>
  </div>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/task_add_form.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new task</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new task</h2>
  <p class="lead">Add first the text of the task. In the next step you will be able to add the possible patron responses.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'trainers:routine_change' routine.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
  </form>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/task_change_form.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ task.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ task.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Responses</strong>
          </div>
          <div class="col-2">
            <strong>Mandatory?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_complete }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your task may have at least <strong>2</strong> responses and maximum <strong>5</strong> responses. Select at least one mandatory response.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'trainers:routine_change' routine.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
    <a href="{% url 'trainers:task_delete' routine.pk task.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
{% endblock %}

The-Project/gym-app/users/templates/users/trainers/task_delete_confirm.html
{% extends 'base.html' %}

{% block title %}Delete Task{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change_list' %}">My Routines</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:routine_change' routine.pk %}">{{ routine.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'trainers:task_change' routine.pk task.pk %}">{{ task.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the task <strong>"{{ task.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'trainers:task_change' routine.pk task.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}